### ISSUE TITLE
Display error message if no database present

### ISSUE THREAD

**Issue by step21** [step21/poerelief#9]
Right now, if no database is present or the database connection cannot be established, SQLAlchemy just gives an error as if the table etc selected for is not there, but doesn't say anything about the db as such.
It would be great if this could be replaced with a proper error, at least for development / if debug = True.

**Comment by shramesh** [comment]
@step21 Where would you want the error message to show up? As an alert/pop-up in the front-end?

**Comment by step21** [comment]
I think on console / error log would be enough. Doesn't/shouldn't be on website. Also sorry for the description being in German. :)

**Comment by shramesh** [comment]
Check if this works - #15.
